spring:
  application:
    name: ytoj-backend-gateway
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
    gateway:
      routes:
        - id: ytoj-backend-user-service
          uri: lb://ytoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: ytoj-backend-question-service
          uri: lb://ytoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: ytoj-backend-judge-service
          uri: lb://ytoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  main:
    web-application-type: reactive
server:
  port: 10010
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2


